AIStream-Peelout/flow-forecast

- .gitignore
- README.md
- flood_forecast/da_rnn/modules.py
- flood_forecast/preprocessing/preprocess_da_rnn.py
- tests/test_da_rnn.py
- tests/test_preprocessing.py
This should fix the tests that failed in master-- (all of them are in the da_rnn stuff) hopefully my assumptions about what is going on in da_rnn is correct...
I have also moved some of the saved outputs from the tests to use tempdirectory so it's a bit less messy when you run tests locally
> attempt to Fix failing tests on master

- flood_forecast/explain_model_output.py
- flood_forecast/plot_functions.py
In this PR, subplots of heatmaps per feature are removed. Instead, each feature heatmap is logged as one figure.
> replace subplots with individual plotly figures

- docs/source/basic_utils.rst
- docs/source/buil_dataset.rst
- docs/source/closest_station.rst
- docs/source/conf.py
- docs/source/custom_opt.rst
- docs/source/custom_types.rst
- docs/source/data_converter.rst
- docs/source/dummy_torch.rst
- docs/source/evaluator.rst
- docs/source/interpolate_preprocess.rst
- docs/source/long_train.rst
- docs/source/lower_upper_config.rst
- docs/source/model.rst
- docs/source/model_dict_function.rst
- docs/source/modules.rst
- docs/source/multi_head_base.rst
- docs/source/pre_dict.rst
- docs/source/preprocess_da_rnn.rst
- docs/source/preprocess_metadata.rst
- docs/source/process_usgs.rst
- docs/source/pytorch_training.rst
- docs/source/temporal_feats.rst
- docs/source/time_model.rst
- docs/source/train_da.rst
- docs/source/trainer.rst
- docs/source/transformer_basic.rst
- docs/source/transformer_xl.rst
- docs/source/utils.rst
- docs/source/utils_da.rst
Fixes to remove python auto-documentation
> 'readthedocs_fix'

- README.md
Basic fixes to the readme file.
> merge into master readme

- flood_forecast/custom/custom_opt.py
Added l1 and orthogonal regularizations
> l1 and orgthogonal regularization

- flood_forecast/meta_models/merging_model.py
- flood_forecast/transformer_xl/transformer_basic.py
- flood_forecast/transformer_xl/transformer_bottleneck.py
- tests/meta_data_test.json
> Bottleneck

- flood_forecast/basic/linear_regression.py
- flood_forecast/explain_model_output.py
- flood_forecast/meta_models/merging_model.py
- flood_forecast/pytorch_training.py
- flood_forecast/transformer_xl/transformer_basic.py
> Fixes to DA-RNN for GPU

- .circleci/config.yml
- docs/source/basic_ae.rst
This PR fixes an issue with CircleCI failing due to problems with the `six` package.
> Force reinstalling and documentation

- .circleci/config.yml
- flood_forecast/evaluator.py
- flood_forecast/pytorch_training.py
- flood_forecast/transformer_xl/transformer_bottleneck.py
This PR aims to address a bug in the transformer and evaluator
> Fix transformer bugs

- .circleci/config.yml
- flood_forecast/evaluator.py
- tests/da_meta.json
Mainly opening this to see what happens with the unit test. This fixes a bug related to not plotting the ci and print
> add dropout to 0.4

- flood_forecast/deployment/inference.py
- flood_forecast/meta_train.py
- flood_forecast/plot_functions.py
- tests/test_deployment.py
> adding file saving

- flood_forecast/deployment/inference.py
- flood_forecast/model_dict_function.py
- flood_forecast/pre_dict.py
- flood_forecast/time_model.py
- flood_forecast/trainer.py
- flood_forecast/utils.py
- tests/da_rnn.json
- tests/transformer_bottleneck.json
> Normalizer

- flood_forecast/pytorch_training.py
- tests/meta_data_test.json
This PR will eventually support a supervised auto-encoder style for the meta-data.
> [WIP] Begin support of supervised auto encoder 

- flood_forecast/basic/linear_regression.py
- flood_forecast/custom/custom_opt.py
- tests/test_multitask_decoder.py
> fixes to dumb bugs

- .flake8
- README.md
- flood_forecast/README.md
- flood_forecast/da_rnn/model.py
- flood_forecast/da_rnn/utils.py
- flood_forecast/preprocessing/eco_gage_set.py
- flood_forecast/pytorch_training.py
- flood_forecast/transformer_xl/dummy_torch.py
- tests/time_model_test.py
> Adding activation

- docs/source/training_utils.rst
- flood_forecast/deployment/inference.py
- flood_forecast/evaluator.py
- flood_forecast/meta_models/basic_ae.py
- flood_forecast/plot_functions.py
- flood_forecast/preprocessing/temporal_feats.py
- flood_forecast/time_model.py
- flood_forecast/trainer.py
- flood_forecast/transformer_xl/dummy_torch.py
- tests/pytorc_train_tests.py
- tests/test_plot.py
> Fixes to test data 1

- flood_forecast/evaluator.py
- flood_forecast/preprocessing/pytorch_loaders.py
- flood_forecast/pytorch_training.py
The goal of this PR is to fix several extraneous print states and warnings associated.
> Fixes print statements and logging warnings

- flood_forecast/preprocessing/pytorch_loaders.py
- flood_forecast/trainer.py
- requirements.txt
This PR aims to accomplish three things:
> Supporting plotting without CI and updating docs

- docs/source/transformer_bottleneck.rst
- flood_forecast/evaluator.py
- flood_forecast/model_dict_function.py
- flood_forecast/pytorch_training.py
- flood_forecast/temporal_decoding.py
- flood_forecast/transformer_xl/informer.py
- tests/test_attn.py
- tests/test_informer.py
> Final Final Informer model additions

- README.md
- flood_forecast/evaluator.py
- flood_forecast/gcp_integration/basic_utils.py
- flood_forecast/preprocessing/interpolate_preprocess.py
- flood_forecast/preprocessing/pytorch_loaders.py
- flood_forecast/preprocessing/temporal_feats.py
- flood_forecast/temporal_decoding.py
- flood_forecast/time_model.py
- flood_forecast/trainer.py
- flood_forecast/training_utils.py
- requirements.txt
- setup.py
- tests/custom_encode.json
- tests/full_transformer.json
- tests/time_model_test.py
- tests/transformer_bottleneck.json
This PR aims to provide interpretability support for SHAP.
> Informer Compatibility with SHAP

- flood_forecast/transformer_xl/transformer_basic.py
- Removed an unnecessary if/else block
- Added a docstring for the SimpleTransformer class in Sphinx style. Not all params have descriptions as I wasn't sure what some of them did.
> Transformer update

- flood_forecast/pytorch_training.py
- tests/full_transformer.json
- tests/multi_decoder_test.json
This PR fixes several issues in FF #475 and #482
> fixing shuffe and standardscaler

- flood_forecast/preprocessing/pytorch_loaders.py
- flood_forecast/preprocessing/temporal_feats.py
- flood_forecast/series_id_helper.py
> fixing linting issues
